name: Azule
main: org.Azule.Main
version: 1.0
commands:
  gmc:
    usage: gmc
    description: Sets targeted member to gamemode creative.
    aliases: [gamemodec, creative, gm1]
  gms:
    usage: gms
    aliases: [gamemodes, survival, gm2]
    description: Sets targeted member to gamemode survival.
  gma:
    usage: gma
    aliases: [gamemodea, adventure, gm3]
    description: Sets targeted member to gamemode adventure.
  gmsp:
    usage: gmsp
    aliases: [gamemodesp, spectator, gm4]
    description: Sets targeted member to gamemode spectator.
  heal:
    usage: heal
    aliases: [health]
    description: Compeltely heals targeted member.
  sethealth:
    usage: sethealth
    aliases: [healthset]
    description: Heals a target by a selected amount.
  feed:
    usage: feed
    aliases: [feedplayer]
    description: Completely feeds targeted member.
  fly:
    usage: fly
    aliases: [flight]
    description: Enables and disables the ability of a certain user to fly.
  vanish:
    usage: vanish
    aliases: [v]
    description: Vanishes a targeted player.